// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductoSOA.Data;

#nullable disable

namespace ProductoSOA.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260108221904_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductoSOA.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Costo")
                        .HasPrecision(18, 2)
                        .HasColumnType("double precision");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("IdTipo")
                        .HasColumnType("integer");

                    b.Property<double>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("IdTipo");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("ProductoSOA.Models.TipoProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("TiposProducto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Tipo = "Electrónica"
                        },
                        new
                        {
                            Id = 2,
                            Tipo = "Ropa"
                        },
                        new
                        {
                            Id = 3,
                            Tipo = "Alimentos"
                        });
                });

            modelBuilder.Entity("ProductoSOA.Models.Producto", b =>
                {
                    b.HasOne("ProductoSOA.Models.TipoProducto", "TipoProducto")
                        .WithMany()
                        .HasForeignKey("IdTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoProducto");
                });
#pragma warning restore 612, 618
        }
    }
}
